### ISSUE TITLE
python test code returns 0

### ISSUE THREAD

**Issue by ryanmjordan** [Sanderi44/Lidar-Lite#5]
I have used this code before and it worked well. Now it only returns 0 as the distance and velocity. I have all of my Interfaces enabled on the Pi 3 B. Any ideas?

**Comment by Sanderi44** [comment]
Hi Ryan,

I would recommend first checking if all of the cables are securely plugged
in.  Sometimes a loose wire can cause a problem like this.  Otherwise, I
have not used the Pi 3 B, so I cannot say as to how it might be acting
different than the older Pi's.  Maybe try different GPIO?

Sander

**Comment by santosh9sanjeev** [comment]
Hi
 Did you guys find a solution?
I too am facing the same issue of getting 0 as a value, when using raspberryPi 3B for distance and velocity...
